import type { Metadata } from 'next'
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import {NavBar} from "@/components/NavBar";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <NavBar />
      <main>
        {children}
      </main>
      </body>
    </html>
  )
}
