name: Java CI with Gradle

on:
  push:
    paths:
      - "bookmark-api/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "bookmark-api/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-bookmarker-api:
    name: Build bookmarker-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmark-api
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./bookmark-api

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./bookmark-api

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with Jib
        if: github.ref == 'refs/heads/main'
        run: ./gradlew jib --image=${{ secrets.DOCKER_USERNAME }}/bookmarker-api
        working-directory: ./bookmark-api
